name: build-and-release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    # tags:
    #   - v*
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    # if: "startsWith(github.ref, 'refs/tags/')"
    # if: "contains(github.event.head_commit.message, 'release:')"
    strategy:
      matrix:
        # https://github.com/actions/runner-images
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install system deps
        # https://github.com/actions/runner-images/blob/win22/20230402.1/images/win/Windows2022-Readme.md
        if: matrix.os == 'windows-latest'
        # https://github.com/nodejs/node-gyp/issues/1587
        run: |
          yarn config list
          yarn config set msvs_version 2022 --global

      - name: Global dependency
        run: |
          yarn cache clean
          yarn global add node-gyp
          yarn global add @vue/cli
      
      - name: Clear cache
        if: matrix.os == 'windows-latest'
        # https://github.com/nodejs/node-gyp/issues/2482
        run: |
          $path = "$env:LocalAppData\node-gyp\Cache"
          if (Test-Path -LiteralPath $path) {
            Remove-Item -LiteralPath $path -Recurse -Verbose
          } else {
            "Path doesn't exist: $path"
          }
      
      - name: Install
        run: |
          yarn cache clean
          yarn install --network-timeout 100000
          yarn run clean
          yarn run init
          yarn run build-py
          yarn run electron:build -p always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}